package user.pojo;
// Generated Mar 31, 2017 2:05:58 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Systemuser generated by hbm2java
 */
@Entity
@Table(name = "SYSTEMUSER", schema = "dbo", catalog = "HERP"
)
public class Systemuser implements java.io.Serializable {

    private int id;
    private String maNhanVien;
    private String ho;
    private String ten;
    private String matKhau;
    private Integer gioiTinh;
    private String ngaySinh;
    private String noiSinh;
    private String diaChiThuongTru;
    private String diaChiTamTru;
    private String hinhAnh;
    private Set userdiplomas = new HashSet(0);

    public Systemuser() {
    }

    public Systemuser(int id) {
        this.id = id;
    }

    public Systemuser(int id, String maNhanVien, String ho, String ten, String matKhau, Integer gioiTinh, String ngaySinh, String noiSinh, String diaChiThuongTru, String diaChiTamTru, String hinhAnh, Set userdiplomas) {
        this.id = id;
        this.maNhanVien = maNhanVien;
        this.ho = ho;
        this.ten = ten;
        this.matKhau = matKhau;
        this.gioiTinh = gioiTinh;
        this.ngaySinh = ngaySinh;
        this.noiSinh = noiSinh;
        this.diaChiThuongTru = diaChiThuongTru;
        this.diaChiTamTru = diaChiTamTru;
        this.hinhAnh = hinhAnh;
        this.userdiplomas = userdiplomas;
    }

    @Id

    @Column(name = "Id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "MaNhanVien", length = 32)
    public String getMaNhanVien() {
        return this.maNhanVien;
    }

    public void setMaNhanVien(String maNhanVien) {
        this.maNhanVien = maNhanVien;
    }

    @Column(name = "Ho")
    public String getHo() {
        return this.ho;
    }

    public void setHo(String ho) {
        this.ho = ho;
    }

    @Column(name = "Ten")
    public String getTen() {
        return this.ten;
    }

    public void setTen(String ten) {
        this.ten = ten;
    }

    @Column(name = "MatKhau")
    public String getMatKhau() {
        return this.matKhau;
    }

    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }

    @Column(name = "GioiTinh")
    public Integer getGioiTinh() {
        return this.gioiTinh;
    }

    public void setGioiTinh(Integer gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    @Column(name = "NgaySinh")
    public String getNgaySinh() {
        return this.ngaySinh;
    }

    public void setNgaySinh(String ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    @Column(name = "NoiSinh")
    public String getNoiSinh() {
        return this.noiSinh;
    }

    public void setNoiSinh(String noiSinh) {
        this.noiSinh = noiSinh;
    }

    @Column(name = "DiaChiThuongTru")
    public String getDiaChiThuongTru() {
        return this.diaChiThuongTru;
    }

    public void setDiaChiThuongTru(String diaChiThuongTru) {
        this.diaChiThuongTru = diaChiThuongTru;
    }

    @Column(name = "DiaChiTamTru")
    public String getDiaChiTamTru() {
        return this.diaChiTamTru;
    }

    public void setDiaChiTamTru(String diaChiTamTru) {
        this.diaChiTamTru = diaChiTamTru;
    }

    @Column(name = "HinhAnh")
    public String getHinhAnh() {
        return this.hinhAnh;
    }

    public void setHinhAnh(String hinhAnh) {
        this.hinhAnh = hinhAnh;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "systemuser")
    public Set getUserdiplomas() {
        return this.userdiplomas;
    }

    public void setUserdiplomas(Set userdiplomas) {
        this.userdiplomas = userdiplomas;
    }

}
