package user.pojo;
// Generated Mar 31, 2017 2:05:58 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userdiploma generated by hbm2java
 */
@Entity
@Table(name = "USERDIPLOMA", schema = "dbo", catalog = "HERP"
)
public class Userdiploma implements java.io.Serializable {

    private int id;
    private Systemuser systemuser;
    private String tenBangCap;
    private String ngayCap;
    private String noiCap;

    public Userdiploma() {
    }

    public Userdiploma(int id) {
        this.id = id;
    }

    public Userdiploma(int id, Systemuser systemuser, String tenBangCap, String ngayCap, String noiCap) {
        this.id = id;
        this.systemuser = systemuser;
        this.tenBangCap = tenBangCap;
        this.ngayCap = ngayCap;
        this.noiCap = noiCap;
    }

    @Id

    @Column(name = "Id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UserId")
    public Systemuser getSystemuser() {
        return this.systemuser;
    }

    public void setSystemuser(Systemuser systemuser) {
        this.systemuser = systemuser;
    }

    @Column(name = "TenBangCap")
    public String getTenBangCap() {
        return this.tenBangCap;
    }

    public void setTenBangCap(String tenBangCap) {
        this.tenBangCap = tenBangCap;
    }

    @Column(name = "NgayCap")
    public String getNgayCap() {
        return this.ngayCap;
    }

    public void setNgayCap(String ngayCap) {
        this.ngayCap = ngayCap;
    }

    @Column(name = "NoiCap")
    public String getNoiCap() {
        return this.noiCap;
    }

    public void setNoiCap(String noiCap) {
        this.noiCap = noiCap;
    }

}
